/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BuiltWithRouteImport } from './routes/built-with'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as KoSitemapRouteImport } from './routes/ko/sitemap'
import { Route as KoChangelogRouteImport } from './routes/ko/changelog'
import { Route as KoBuiltWithRouteImport } from './routes/ko/built-with'
import { Route as KoAboutRouteImport } from './routes/ko/about'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiltWithRoute = BuiltWithRouteImport.update({
  id: '/built-with',
  path: '/built-with',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoSitemapRoute = KoSitemapRouteImport.update({
  id: '/ko/sitemap',
  path: '/ko/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const KoChangelogRoute = KoChangelogRouteImport.update({
  id: '/ko/changelog',
  path: '/ko/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const KoBuiltWithRoute = KoBuiltWithRouteImport.update({
  id: '/ko/built-with',
  path: '/ko/built-with',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAboutRoute = KoAboutRouteImport.update({
  id: '/ko/about',
  path: '/ko/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-with': typeof BuiltWithRoute
  '/changelog': typeof ChangelogRoute
  '/sitemap': typeof SitemapRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/changelog': typeof KoChangelogRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/': typeof KoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-with': typeof BuiltWithRoute
  '/changelog': typeof ChangelogRoute
  '/sitemap': typeof SitemapRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/changelog': typeof KoChangelogRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko': typeof KoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built-with': typeof BuiltWithRoute
  '/changelog': typeof ChangelogRoute
  '/sitemap': typeof SitemapRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/built-with': typeof KoBuiltWithRoute
  '/ko/changelog': typeof KoChangelogRoute
  '/ko/sitemap': typeof KoSitemapRoute
  '/ko/': typeof KoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/built-with'
    | '/changelog'
    | '/sitemap'
    | '/ko/about'
    | '/ko/built-with'
    | '/ko/changelog'
    | '/ko/sitemap'
    | '/ko/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/built-with'
    | '/changelog'
    | '/sitemap'
    | '/ko/about'
    | '/ko/built-with'
    | '/ko/changelog'
    | '/ko/sitemap'
    | '/ko'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/built-with'
    | '/changelog'
    | '/sitemap'
    | '/ko/about'
    | '/ko/built-with'
    | '/ko/changelog'
    | '/ko/sitemap'
    | '/ko/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuiltWithRoute: typeof BuiltWithRoute
  ChangelogRoute: typeof ChangelogRoute
  SitemapRoute: typeof SitemapRoute
  KoAboutRoute: typeof KoAboutRoute
  KoBuiltWithRoute: typeof KoBuiltWithRoute
  KoChangelogRoute: typeof KoChangelogRoute
  KoSitemapRoute: typeof KoSitemapRoute
  KoIndexRoute: typeof KoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built-with': {
      id: '/built-with'
      path: '/built-with'
      fullPath: '/built-with'
      preLoaderRoute: typeof BuiltWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/sitemap': {
      id: '/ko/sitemap'
      path: '/ko/sitemap'
      fullPath: '/ko/sitemap'
      preLoaderRoute: typeof KoSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/changelog': {
      id: '/ko/changelog'
      path: '/ko/changelog'
      fullPath: '/ko/changelog'
      preLoaderRoute: typeof KoChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/built-with': {
      id: '/ko/built-with'
      path: '/ko/built-with'
      fullPath: '/ko/built-with'
      preLoaderRoute: typeof KoBuiltWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/about': {
      id: '/ko/about'
      path: '/ko/about'
      fullPath: '/ko/about'
      preLoaderRoute: typeof KoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuiltWithRoute: BuiltWithRoute,
  ChangelogRoute: ChangelogRoute,
  SitemapRoute: SitemapRoute,
  KoAboutRoute: KoAboutRoute,
  KoBuiltWithRoute: KoBuiltWithRoute,
  KoChangelogRoute: KoChangelogRoute,
  KoSitemapRoute: KoSitemapRoute,
  KoIndexRoute: KoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
