/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SoundBlueRouteImport } from './routes/sound-blue'
import { Route as DialogueRouteImport } from './routes/dialogue'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as JaIndexRouteImport } from './routes/ja/index'
import { Route as KoToolsRouteImport } from './routes/ko/tools'
import { Route as KoSoundBlueRouteImport } from './routes/ko/sound-blue'
import { Route as KoDialogueRouteImport } from './routes/ko/dialogue'
import { Route as KoAboutRouteImport } from './routes/ko/about'
import { Route as JaToolsRouteImport } from './routes/ja/tools'
import { Route as JaSoundBlueRouteImport } from './routes/ja/sound-blue'
import { Route as JaDialogueRouteImport } from './routes/ja/dialogue'
import { Route as JaAboutRouteImport } from './routes/ja/about'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundBlueRoute = SoundBlueRouteImport.update({
  id: '/sound-blue',
  path: '/sound-blue',
  getParentRoute: () => rootRouteImport,
} as any)
const DialogueRoute = DialogueRouteImport.update({
  id: '/dialogue',
  path: '/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const JaIndexRoute = JaIndexRouteImport.update({
  id: '/ja/',
  path: '/ja/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoToolsRoute = KoToolsRouteImport.update({
  id: '/ko/tools',
  path: '/ko/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const KoSoundBlueRoute = KoSoundBlueRouteImport.update({
  id: '/ko/sound-blue',
  path: '/ko/sound-blue',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDialogueRoute = KoDialogueRouteImport.update({
  id: '/ko/dialogue',
  path: '/ko/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const KoAboutRoute = KoAboutRouteImport.update({
  id: '/ko/about',
  path: '/ko/about',
  getParentRoute: () => rootRouteImport,
} as any)
const JaToolsRoute = JaToolsRouteImport.update({
  id: '/ja/tools',
  path: '/ja/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const JaSoundBlueRoute = JaSoundBlueRouteImport.update({
  id: '/ja/sound-blue',
  path: '/ja/sound-blue',
  getParentRoute: () => rootRouteImport,
} as any)
const JaDialogueRoute = JaDialogueRouteImport.update({
  id: '/ja/dialogue',
  path: '/ja/dialogue',
  getParentRoute: () => rootRouteImport,
} as any)
const JaAboutRoute = JaAboutRouteImport.update({
  id: '/ja/about',
  path: '/ja/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dialogue': typeof DialogueRoute
  '/sound-blue': typeof SoundBlueRoute
  '/tools': typeof ToolsRoute
  '/ja/about': typeof JaAboutRoute
  '/ja/dialogue': typeof JaDialogueRoute
  '/ja/sound-blue': typeof JaSoundBlueRoute
  '/ja/tools': typeof JaToolsRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/dialogue': typeof KoDialogueRoute
  '/ko/sound-blue': typeof KoSoundBlueRoute
  '/ko/tools': typeof KoToolsRoute
  '/ja/': typeof JaIndexRoute
  '/ko/': typeof KoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dialogue': typeof DialogueRoute
  '/sound-blue': typeof SoundBlueRoute
  '/tools': typeof ToolsRoute
  '/ja/about': typeof JaAboutRoute
  '/ja/dialogue': typeof JaDialogueRoute
  '/ja/sound-blue': typeof JaSoundBlueRoute
  '/ja/tools': typeof JaToolsRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/dialogue': typeof KoDialogueRoute
  '/ko/sound-blue': typeof KoSoundBlueRoute
  '/ko/tools': typeof KoToolsRoute
  '/ja': typeof JaIndexRoute
  '/ko': typeof KoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dialogue': typeof DialogueRoute
  '/sound-blue': typeof SoundBlueRoute
  '/tools': typeof ToolsRoute
  '/ja/about': typeof JaAboutRoute
  '/ja/dialogue': typeof JaDialogueRoute
  '/ja/sound-blue': typeof JaSoundBlueRoute
  '/ja/tools': typeof JaToolsRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/dialogue': typeof KoDialogueRoute
  '/ko/sound-blue': typeof KoSoundBlueRoute
  '/ko/tools': typeof KoToolsRoute
  '/ja/': typeof JaIndexRoute
  '/ko/': typeof KoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dialogue'
    | '/sound-blue'
    | '/tools'
    | '/ja/about'
    | '/ja/dialogue'
    | '/ja/sound-blue'
    | '/ja/tools'
    | '/ko/about'
    | '/ko/dialogue'
    | '/ko/sound-blue'
    | '/ko/tools'
    | '/ja/'
    | '/ko/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dialogue'
    | '/sound-blue'
    | '/tools'
    | '/ja/about'
    | '/ja/dialogue'
    | '/ja/sound-blue'
    | '/ja/tools'
    | '/ko/about'
    | '/ko/dialogue'
    | '/ko/sound-blue'
    | '/ko/tools'
    | '/ja'
    | '/ko'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dialogue'
    | '/sound-blue'
    | '/tools'
    | '/ja/about'
    | '/ja/dialogue'
    | '/ja/sound-blue'
    | '/ja/tools'
    | '/ko/about'
    | '/ko/dialogue'
    | '/ko/sound-blue'
    | '/ko/tools'
    | '/ja/'
    | '/ko/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DialogueRoute: typeof DialogueRoute
  SoundBlueRoute: typeof SoundBlueRoute
  ToolsRoute: typeof ToolsRoute
  JaAboutRoute: typeof JaAboutRoute
  JaDialogueRoute: typeof JaDialogueRoute
  JaSoundBlueRoute: typeof JaSoundBlueRoute
  JaToolsRoute: typeof JaToolsRoute
  KoAboutRoute: typeof KoAboutRoute
  KoDialogueRoute: typeof KoDialogueRoute
  KoSoundBlueRoute: typeof KoSoundBlueRoute
  KoToolsRoute: typeof KoToolsRoute
  JaIndexRoute: typeof JaIndexRoute
  KoIndexRoute: typeof KoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-blue': {
      id: '/sound-blue'
      path: '/sound-blue'
      fullPath: '/sound-blue'
      preLoaderRoute: typeof SoundBlueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogue': {
      id: '/dialogue'
      path: '/dialogue'
      fullPath: '/dialogue'
      preLoaderRoute: typeof DialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/': {
      id: '/ja/'
      path: '/ja'
      fullPath: '/ja/'
      preLoaderRoute: typeof JaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/tools': {
      id: '/ko/tools'
      path: '/ko/tools'
      fullPath: '/ko/tools'
      preLoaderRoute: typeof KoToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/sound-blue': {
      id: '/ko/sound-blue'
      path: '/ko/sound-blue'
      fullPath: '/ko/sound-blue'
      preLoaderRoute: typeof KoSoundBlueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/dialogue': {
      id: '/ko/dialogue'
      path: '/ko/dialogue'
      fullPath: '/ko/dialogue'
      preLoaderRoute: typeof KoDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/about': {
      id: '/ko/about'
      path: '/ko/about'
      fullPath: '/ko/about'
      preLoaderRoute: typeof KoAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/tools': {
      id: '/ja/tools'
      path: '/ja/tools'
      fullPath: '/ja/tools'
      preLoaderRoute: typeof JaToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/sound-blue': {
      id: '/ja/sound-blue'
      path: '/ja/sound-blue'
      fullPath: '/ja/sound-blue'
      preLoaderRoute: typeof JaSoundBlueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/dialogue': {
      id: '/ja/dialogue'
      path: '/ja/dialogue'
      fullPath: '/ja/dialogue'
      preLoaderRoute: typeof JaDialogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/about': {
      id: '/ja/about'
      path: '/ja/about'
      fullPath: '/ja/about'
      preLoaderRoute: typeof JaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DialogueRoute: DialogueRoute,
  SoundBlueRoute: SoundBlueRoute,
  ToolsRoute: ToolsRoute,
  JaAboutRoute: JaAboutRoute,
  JaDialogueRoute: JaDialogueRoute,
  JaSoundBlueRoute: JaSoundBlueRoute,
  JaToolsRoute: JaToolsRoute,
  KoAboutRoute: KoAboutRoute,
  KoDialogueRoute: KoDialogueRoute,
  KoSoundBlueRoute: KoSoundBlueRoute,
  KoToolsRoute: KoToolsRoute,
  JaIndexRoute: JaIndexRoute,
  KoIndexRoute: KoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
