// Drum Machine Settings

export type DrumId = 'kick' | 'snare' | 'hihat' | 'openhat' | 'clap';

export interface DrumSynthParams {
  pitch: number;
  decay: number;
  tone: number;
  punch: number;
}

export const DRUM_DEFAULTS: Record<DrumId, DrumSynthParams> = {
  kick: { pitch: 60, decay: 0.5, tone: 30, punch: 80 },
  snare: { pitch: 200, decay: 0.2, tone: 50, punch: 60 },
  hihat: { pitch: 8000, decay: 0.05, tone: 90, punch: 40 },
  openhat: { pitch: 8000, decay: 0.3, tone: 80, punch: 50 },
  clap: { pitch: 400, decay: 0.15, tone: 60, punch: 70 },
};

export const DRUM_SOUNDS: { id: DrumId; name: string; icon: string }[] = [
  { id: 'kick', name: 'Kick', icon: '🔈' },
  { id: 'snare', name: 'Snare', icon: '🥁' },
  { id: 'hihat', name: 'Hi-Hat', icon: '🎛️' },
  { id: 'openhat', name: 'Open Hat', icon: '🔔' },
  { id: 'clap', name: 'Clap', icon: '👏' },
];

export interface DrumMachineSettings {
  bpm: number;
  steps: number;
  pattern: Record<DrumId, boolean[]>;
  volume: number;
  swing: number;
  metronomeEnabled: boolean;
  synth: Record<DrumId, DrumSynthParams>;
}

export const createEmptyPattern = (steps: number): Record<DrumId, boolean[]> => ({
  kick: Array(steps).fill(false),
  snare: Array(steps).fill(false),
  hihat: Array(steps).fill(false),
  openhat: Array(steps).fill(false),
  clap: Array(steps).fill(false),
});

// Preset patterns from HTML reference
export type PresetName = 'empty' | 'techno' | 'house' | 'trap' | 'breakbeat' | 'minimal';

export const PRESET_PATTERNS: Record<
  PresetName,
  { name: string; pattern: Record<DrumId, boolean[]> }
> = {
  empty: {
    name: 'Empty',
    pattern: createEmptyPattern(16),
  },
  techno: {
    name: 'Techno',
    pattern: {
      kick: [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      snare: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      hihat: [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      openhat: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      clap: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
    },
  },
  house: {
    name: 'House',
    pattern: {
      kick: [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      snare: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      hihat: [
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
      ],
      openhat: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      clap: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
    },
  },
  trap: {
    name: 'Trap',
    pattern: {
      kick: [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      snare: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      hihat: [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
      ],
      openhat: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      clap: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
    },
  },
  breakbeat: {
    name: 'Breakbeat',
    pattern: {
      kick: [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      snare: [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
      ],
      hihat: [
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
      ],
      openhat: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      clap: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    },
  },
  minimal: {
    name: 'Minimal',
    pattern: {
      kick: [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      snare: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      hihat: [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      openhat: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      clap: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    },
  },
};

export const defaultDrumMachineSettings: DrumMachineSettings = {
  bpm: 120,
  steps: 16,
  pattern: createEmptyPattern(16),
  volume: 0.7,
  swing: 0,
  metronomeEnabled: false,
  synth: { ...DRUM_DEFAULTS },
};

export const METRONOME = {
  ACCENT_FREQ: 1500,
  REGULAR_FREQ: 1000,
  CLICK_DURATION: 0.05,
};
