// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/ko": {
    params: {};
  };
  "/ko/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/ko" | "/ko/about";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/ko/home.tsx": {
    id: "routes/ko/home";
    page: "/ko";
  };
  "routes/ko/about.tsx": {
    id: "routes/ko/about";
    page: "/ko/about";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/ko/home": typeof import("./app/routes/ko/home.tsx");
  "routes/ko/about": typeof import("./app/routes/ko/about.tsx");
};