// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/sitemap": {
    params: {};
  };
  "/ko": {
    params: {};
  };
  "/ko/about": {
    params: {};
  };
  "/ko/sitemap": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/sitemap" | "/ko" | "/ko/about" | "/ko/sitemap";
  };
  "routes/($locale)/home.tsx": {
    id: "home-en";
    page: "/";
  } | {
    id: "home-ko";
    page: "/ko";
  };
  "routes/($locale)/about.tsx": {
    id: "about-en";
    page: "/about";
  } | {
    id: "about-ko";
    page: "/ko/about";
  };
  "routes/($locale)/sitemap.tsx": {
    id: "sitemap-en";
    page: "/sitemap";
  } | {
    id: "sitemap-ko";
    page: "/ko/sitemap";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "home-en": typeof import("./app/routes/($locale)/home.tsx");
  "about-en": typeof import("./app/routes/($locale)/about.tsx");
  "sitemap-en": typeof import("./app/routes/($locale)/sitemap.tsx");
  "home-ko": typeof import("./app/routes/($locale)/home.tsx");
  "about-ko": typeof import("./app/routes/($locale)/about.tsx");
  "sitemap-ko": typeof import("./app/routes/($locale)/sitemap.tsx");
};