#!/usr/bin/env tsx
/**
 * Postbuild script - runs after the main build
 *
 * Tasks:
 * 1. Generate sitemap.xml (if not already generated by app)
 * 2. Generate robots.txt (if not already exists)
 * 3. Verify build output
 */

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();

interface AppConfig {
  name: string;
  domain: string;
  buildDir: string;
}

const APPS: AppConfig[] = [
  { name: 'tools', domain: 'tools.soundbluemusic.com', buildDir: 'build/client' },
  { name: 'sound-blue', domain: 'soundbluemusic.com', buildDir: 'build/client' },
  { name: 'dialogue', domain: 'dialogue.soundbluemusic.com', buildDir: 'build/client' },
];

function generateRobotsTxt(domain: string): string {
  return `# https://${domain}/robots.txt
User-agent: *
Allow: /

# Sitemaps
Sitemap: https://${domain}/sitemap.xml

# Disallow admin/api paths (if any)
Disallow: /api/
Disallow: /_/
`;
}

function verifyBuildOutput(appPath: string, appName: string): boolean {
  const buildDir = join(appPath, 'build', 'client');

  if (!existsSync(buildDir)) {
    console.log(`  ⚠️  ${appName}: No build output found`);
    return false;
  }

  const indexHtml = join(buildDir, 'index.html');
  if (!existsSync(indexHtml)) {
    console.log(`  ⚠️  ${appName}: No index.html found`);
    return false;
  }

  // Check for essential files
  const essentialFiles = ['index.html'];
  const missingFiles = essentialFiles.filter((f) => !existsSync(join(buildDir, f)));

  if (missingFiles.length > 0) {
    console.log(`  ⚠️  ${appName}: Missing files: ${missingFiles.join(', ')}`);
    return false;
  }

  // Count HTML files (prerendered pages)
  const htmlFiles = countFiles(buildDir, '.html');
  const jsFiles = countFiles(buildDir, '.js');
  const cssFiles = countFiles(buildDir, '.css');

  console.log(`  ✅ ${appName}: ${htmlFiles} HTML, ${jsFiles} JS, ${cssFiles} CSS`);
  return true;
}

function countFiles(dir: string, extension: string): number {
  let count = 0;

  const items = readdirSync(dir);
  for (const item of items) {
    const fullPath = join(dir, item);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      count += countFiles(fullPath, extension);
    } else if (item.endsWith(extension)) {
      count++;
    }
  }

  return count;
}

function ensureRobotsTxt(appConfig: AppConfig): void {
  const appPath = join(ROOT, 'apps', appConfig.name);
  const buildDir = join(appPath, appConfig.buildDir);
  const robotsPath = join(buildDir, 'robots.txt');

  if (!existsSync(buildDir)) {
    return;
  }

  if (!existsSync(robotsPath)) {
    const content = generateRobotsTxt(appConfig.domain);
    writeFileSync(robotsPath, content);
    console.log(`  📝 Generated robots.txt for ${appConfig.name}`);
  }
}

function checkSitemapExists(appConfig: AppConfig): void {
  const appPath = join(ROOT, 'apps', appConfig.name);
  const buildDir = join(appPath, appConfig.buildDir);
  const sitemapPath = join(buildDir, 'sitemap.xml');

  if (!existsSync(buildDir)) {
    return;
  }

  if (existsSync(sitemapPath)) {
    const content = readFileSync(sitemapPath, 'utf-8');
    const urlCount = (content.match(/<url>/g) || []).length;
    console.log(`  ✅ ${appConfig.name}: sitemap.xml (${urlCount} URLs)`);
  } else {
    console.log(`  ⚠️  ${appConfig.name}: No sitemap.xml found`);
  }
}

async function main() {
  console.log('🚀 Running postbuild...\n');

  // Step 1: Verify build outputs
  console.log('🔍 Verifying build outputs...');
  let allValid = true;

  for (const app of APPS) {
    const appPath = join(ROOT, 'apps', app.name);
    if (existsSync(appPath)) {
      const valid = verifyBuildOutput(appPath, app.name);
      if (!valid) allValid = false;
    }
  }

  console.log('');

  // Step 2: Ensure robots.txt
  console.log('🤖 Checking robots.txt...');
  for (const app of APPS) {
    ensureRobotsTxt(app);
  }

  console.log('');

  // Step 3: Check sitemaps
  console.log('🗺️  Checking sitemaps...');
  for (const app of APPS) {
    checkSitemapExists(app);
  }

  console.log('');

  if (allValid) {
    console.log('✅ Postbuild complete!');
  } else {
    console.log('⚠️  Postbuild completed with warnings');
  }
}

main().catch((error) => {
  console.error('Postbuild failed:', error);
  process.exit(1);
});
